### ISSUE TITLE
Code for the figures

### ISSUE THREAD

**Issue by zhiyuzz** [bremen79/parameterfree#1]
Hi Francesco, could you please include some sample code that generates the figures? Would make further testing a bit easier. Thanks!

**Comment by bremen79** [comment]
Hi Zhiyu,
I actually have a gigantic framework to run batches of experiments, it might be too much of a mess to include.
However, I can include some simple deep learning example code.
Give me a couple of days.

**Comment by bremen79** [comment]
Hi Zhiyu,

In "examples" I added the code I used to run the experiments on FashionMNIST (minus the plotting).
Please take a look at it and see if it works for you.

**Comment by zhiyuzz** [comment]
It works for me, thanks for your quick response!
